### ISSUE TITLE
Hexo NexT主题内添加相册功能 | asdfv1929 's Home

### ISSUE THREAD

**Issue by asdfv1929** [asdfv1929/asdfv1929.github.io#17]
https://asdfv1929.github.io/2018/05/26/next-add-photos/ 

 给博客添加一个相册页面，以展示自己拍摄的一些照片  (≖ᴗ≖)✧

**Comment by xiachongzhe** [comment]
为什么不用七牛云当做博客图床，这样随着图片以后越来越多，加载中响应速度会越来越慢，导致崩溃！

**Comment by asdfv1929** [comment]
> @xiachongzhe
> 为什么不用七牛云当做博客图床，这样随着图片以后越来越多，加载中响应速度会越来越慢，导致崩溃！

在博客其他博文中的图片，我都是以图床链接的方式访问图片的。相册的话，也有想过用图床，但一方面是七牛云貌似是收费制，且上传图片的大小有限制，另一方面是我暂时也不需要展示太多照片，所以就先就考虑了这种方法。后期若速度上有些问题，我再改变方式。

**Comment by asdfv1929** [comment]
> @xiachongzhe
> 为什么不用七牛云当做博客图床，这样随着图片以后越来越多，加载中响应速度会越来越慢，导致崩溃！

而且。我这些照片并不是放在博客的仓库里，是另新建的一个存储照片的库，源码里也是通过链接访问里面的图片的。现访问相册，图片显示的较慢，大致原因是照片太大，都几兆以上的。后期会想办法压缩上传。

**Comment by Lruihao** [comment]
看你最近有更新，想问你一些问题，当然很期待收到你的回复，我的博客地址https://lruihao.github.io/，里面有我的联系方式
1.怎么创建相册库啊，创建了怎么配置，和上传等
2.你的这个评论怎么添加的呀

**Comment by asdfv1929** [comment]
> @Lruihao
> 看你最近有更新，想问你一些问题，当然很期待收到你的回复，我的博客地址https://lruihao.github.io/
> 里面有我的联系方式
> 1.怎么创建相册库啊，创建了怎么配置，和上传等
> 2.你的这个评论怎么添加的呀

相册的话，就是以本篇博文的流程来进行操作的。评论的话，请参考这篇 https://asdfv1929.github.io/2018/01/20/gitalk/

**Comment by zhengmengping** [comment]
我按照你博客里的方法试着做了一下相册，可是图片加载不出来，获取不到数据，想跟你交流一下，我微信号zmp19940917，希望博主有空的时候能跟我交流下

**Comment by zhengmengping** [comment]
你photo下的index.md文件写了什么

**Comment by asdfv1929** [comment]
> @zhengmengping
> 我按照你博客里的方法试着做了一下相册，可是图片加载不出来，获取不到数据，想跟你交流一下，我微信号zmp19940917，希望博主有空的时候能跟我交流下

加你了

**Comment by leirock** [comment]
十分感谢！我按照你的方法创建好了，不过我另外做了改进，就是不用直接去修改主题源文件，而是直接加在主题提供的自定义文档里，这样可能操作起来更方便。我的改进可以查看：[Hexo NexT 博客增加瀑布流相册页面](https://pinlyu.com/post/31/)。

另外你的博客中文字体是不是没有配置好，导致我这里用 macOS Safari 或者 Chrome 显示起来有几个字都不是正常的简体字字体结构。比如下面截图里的添加的“添”，还有直接的“直”等等。
<img width="1174" src="https://user-images.githubusercontent.com/19180725/41206943-30c386bc-6d3f-11e8-887d-37445a875859.png">

**Comment by asdfv1929** [comment]
> @dldylan
> 十分感谢！我按照你的方法创建好了，不过我另外做了改进，就是不用直接去修改主题源文件，而是直接加在主题提供的自定义文档里，这样可能操作起来更方便。我的改进可以查看：[Hexo NexT 博客增加瀑布流相册页面 | BanbanRamble](https://blog.dongleizhang.com/posts/3720dafc/)。
> 
> 另外你的博客中文字体是不是没有配置好，导致我这里用 macOS Safari 或者 Chrome 显示起来有几个字都不是正常的简体字字体结构。比如下面截图里的添加的“添”，还有直接的“直”等等。
> <img width="1174" src="https://user-images.githubusercontent.com/19180725/41206943-30c386bc-6d3f-11e8-887d-37445a875859.png">

确实是可以直接加载主题中自定义文档里，不过我为了区分开来不同的作用，所以另建文件。字体的话，我目前就是一直用的默认字体，没改过，可能有些字体的显示方面和平常看到的不一样。

**Comment by jayliu0472** [comment]
在执行 node tool.js 命令时报错，把第15行的 fs.writeFile 改成 fs.writeFileSync 就好了

**Comment by SeltyL** [comment]
emmm 我按照您的方式试了一下 然而照片页并没有显示照片欸（ 大概是出什么问题了呢...

**Comment by ddabb** [comment]
我的照片也加载不出来，麻烦加我微信 帮我解决一下该问题 谢谢  18664891357

**Comment by asdfv1929** [comment]
> @ddabb
> 我的照片也加载不出来，麻烦加我微信 帮我解决一下该问题 谢谢  18664891357

我想说明一下，，遇到问题，得先自己去找一下问题，或审视步骤，或百度谷歌，最后与他人讨论研究，，而不是说“帮我解决一下问题”

**Comment by AnimatorBullet** [comment]
先谢谢博主~
然后为啥我做完其他大部分正常。。
就是贴出来的图片数量是*2的呢，一张图放两遍，
求助求助，有空还请帮忙分析下>_<
https://acebullet.tk/photos/

**Comment by asdfv1929** [comment]
最近一段时间，我可能没啥时间去弄。你先按步骤再重新检查下，我年后有时间再看


| |
阿斯顿
邮箱：asdfv1929@163.com
|

签名由 网易邮箱大师 定制

在2019年02月02日 23:19，AnimatorBullet 写道：

先谢谢博主~
然后为啥我做完其他大部分正常。。
就是贴出来的图片数量是*2的呢，一张图放两遍，
求助求助，有空还请帮忙分析下>_<
https://acebullet.tk/photos/

**Comment by fengkkk** [comment]
博主我想问一下你这个超过20张可以分页吗？我模仿你的方法捣鼓了一下把图片部署到腾讯云COS上了，但是调试的时候发现好像不能分页，然后我看了一下参考文章，发现那个不是NexT主题。目前暂时解决办法是把20改成了50。但是想问下博主知道NexT可以怎么实现分页吗qaq

**Comment by asdfv1929** [comment]
目前我这个不能分页，，分页的功能得自己去写


| |
阿斯顿
邮箱：asdfv1929@163.com
|

签名由 网易邮箱大师 定制

在2019年02月21日 03:31，Fengkkk 写道：

博主我想问一下你这个超过20张可以分页吗？我模仿你的方法捣鼓了一下把图片部署到腾讯云COS上了，但是调试的时候发现好像不能分页，然后我看了一下参考文章，发现那个不是NexT主题。目前暂时解决办法是把20改成了50。但是想问下博主知道NexT可以怎么实现分页吗qaq

**Comment by fengkkk** [comment]
> 目前我这个不能分页，，分页的功能得自己去写 | | 阿斯顿 邮箱：asdfv1929@163.com | 签名由 网易邮箱大师 定制 在2019年02月21日 03:31，Fengkkk 写道： 博主我想问一下你这个超过20张可以分页吗？我模仿你的方法捣鼓了一下把图片部署到腾讯云COS上了，但是调试的时候发现好像不能分页，然后我看了一下参考文章，发现那个不是NexT主题。目前暂时解决办法是把20改成了50。但是想问下博主知道NexT可以怎么实现分页吗qaq — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

qaq好的好的，我以为是我部署的姿势有问题呢。现在暂时还是先通过改offset将图片放在一页吧，以后图多了再打算，谢谢博主~

**Comment by JohnDoeo** [comment]
老哥，我按照你的方法执行node tool.js的时候报了这个错：
```
fs.js:129
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1159:14)
    at iterator (E:\blog-generator\uploadPhotos\tool.js:14:16)
    at E:\blog-generator\uploadPhotos\tool.js:28:6
    at FSReqWrap.oncomplete (fs.js:141:20)
```
不知道该怎么解决了

**Comment by asdfv1929** [comment]
关于NodeJs这块，我也不是太懂，抱歉。建议先定位错误，然后百度看看错误的原因，是否有解决办法

发送自 Windows 10 版邮件应用

发件人: JohnDoeo
发送时间: 2019年2月23日 11:40
收件人: asdfv1929/asdfv1929.github.io
抄送: asdfv1929; Author
主题: Re: [asdfv1929/asdfv1929.github.io] Hexo NexT主题内添加相册功能 | asdfv1929 's Home (#17)

老哥，我按照你的方法执行node tool.js的时候报了这个错：
fs.js:129

  throw new ERR_INVALID_CALLBACK();

  ^



TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

    at maybeCallback (fs.js:129:9)

    at Object.writeFile (fs.js:1159:14)

    at iterator (E:\blog-generator\uploadPhotos\tool.js:14:16)

    at E:\blog-generator\uploadPhotos\tool.js:28:6

    at FSReqWrap.oncomplete (fs.js:141:20)

不知道该怎么解决了

**Comment by univeryinli** [comment]
博主能教一下如何改成图床的形式展示相册么

**Comment by hac135** [comment]
你好，我按你的方法创建的相册可以显示，非常感谢。不过有个小问题，请问下，相片靠左，没有居中，请问要在哪里修改才能和您的一样呀

**Comment by Maomao-A** [comment]
你好 我在执行node tool.js命令时，报了个错 百度没能解决 能恳请您帮下忙嘛(纯小白)
$ node tool.js
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'D:\blog\maomao-aBlog\tool.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:686:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
